# Generated by Django 3.2 on 2022-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
