# Generated by Django 3.2 on 2022-05-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220501_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='categorie',
            new_name='sous_categorie',
        ),
    ]
