# Generated by Django 3.2 on 2022-05-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_categorie_produit_sous_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorie',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
